In [2]:

%tensorflow_version 2.x

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [3]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.11/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [4]:
tf.__version__

'2.18.0'

In [5]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [6]:
x= tf.constant(10)
x
print(x.numpy())


10


#Why TensorFlow tensors show numpy=...
#The numpy=... part is a convenient view that shows the actual value of the tensor converted to a NumPy-compatible format.

#This doesn't mean TensorFlow is literally storing everything inside NumPy — it just shows how you can access the tensor's value as a NumPy object using the .numpy() method.



In [88]:
y= tf.constant(10.5)
y
print(y.numpy())


10.5


In [90]:
z=tf.constant("India")
z
print(z.numpy())

b'India'


In [9]:
z=tf.constant(True)
z
print(z.numpy())

True


In [105]:

a = tf.constant(5.0) # Immutable tensor


b = tf.Variable("Indiathelove")# Mutable tensor
b

a.assign(10.0)
b.assign("DelhiuBeauty")
print(a.numpy())
# print(b.numpy())


AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [110]:
#1D-Tensor
s=tf.constant([1, 2, 3, 4, 5, 6])
s
# print(s.numpy())

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [113]:
#2D-Tensor
s=tf.constant([[1, 2, 3, 4, 5, 6],[5,8,3,2,9,12]])
s

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 5,  8,  3,  2,  9, 12]], dtype=int32)>

In [12]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
tf.constant(a)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [13]:
t_2d=tf.constant([[1,2],[3,4]])
t_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [14]:
t_1d=tf.constant([1,2,3,4])
t_1d

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [15]:
t_2d_1=tf.constant([1,2,3,4],shape=(2,2),dtype="int32")
t_2d_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [16]:
t_3d_1=tf.constant([[[1,2],[2,3],[3,4]]],dtype="float32")
t_3d_1

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[1., 2.],
        [2., 3.],
        [3., 4.]]], dtype=float32)>

In [17]:
type(t_3d_1)

tensorflow.python.framework.ops.EagerTensor

In [18]:
t_3d_1.shape

TensorShape([1, 3, 2])

# Tensorflow Variable



In [19]:
# Variable constructor requires an initial value for the variable
# which can be a tensor of any type & shape.
# This initial value defines the type & shape of the variable.
# After construction the type & shape of the variable are fixed.

In [20]:
import tensorflow as tf

In [21]:
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [22]:
x=tf.Variable([1,2,3,4])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [23]:
x.name


'Variable:0'

In [24]:
x.shape

TensorShape([4])

In [25]:
x.dtype

tf.int32

In [26]:
y=tf.Variable([1.0,2,3.3,4])

In [27]:
y

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1. , 2. , 3.3, 4. ], dtype=float32)>

In [28]:
z=tf.Variable(True,False)

In [29]:
z

<tf.Variable 'Variable:0' shape=() dtype=bool, numpy=True>

In [30]:
t_con=tf.constant([1,2,3,4])

In [31]:
t_con

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [32]:
tf.Variable(t_con)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

# Create Tensorflow variable with different Shape

In [33]:
t_2d=tf.Variable([[2,3],[4,5]])
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [34]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [35]:
tf.reshape(x,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [36]:
# Get index of highest value

In [37]:
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [38]:
tf.argmax(t_2d)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [39]:
# Viewed/Convert as a Tensor

In [40]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [41]:
tf.convert_to_tensor(x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [42]:
tf.convert_to_tensor(t_2d)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [43]:
# Change/Assign New Value to Tensor

In [44]:
x=tf.Variable([1,2,3,4])
x


<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [45]:
x.assign([4,6,2,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 8], dtype=int32)>

In [46]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 8], dtype=int32)>

In [47]:
x.assign([4,6,2,9])


<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 9], dtype=int32)>

In [48]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 9], dtype=int32)>

In [49]:
# Assign Variable with another Memory

In [50]:
x.assign_add([4,6,2,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 8, 12,  4, 17], dtype=int32)>

In [51]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([ 8, 12,  4, 17], dtype=int32)>

Tensorflow Math **Modules**

In [52]:
import tensorflow as tf
import numpy as np

In [53]:
a=10
b=20

In [54]:
a+b

30

In [55]:
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [56]:
#Addition of Two List

l1=[1,2,3,4]
l2=[5,6,7,8]
tf.add(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12], dtype=int32)>

In [57]:
# Addition of Two tuple
t1=(2,3,4,5)
t2=(5,6,7,8)
tf.add(t1,t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 7,  9, 11, 13], dtype=int32)>

In [58]:
l1=[1,2,3,4]
a=10
tf.add(l1,a)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([11, 12, 13, 14], dtype=int32)>

In [59]:
# Given a tensor x and a tensor y, this operation x^y computes for corresponding elements in x and y

x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [60]:
# tf.math.abs

# real number
x = tf.constant([-2.25, 3.25])
tf.abs(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [61]:
# complex number
x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [62]:
# tf.math.subtract

x = [1, 2, 3, 4, 5]
y = 1
tf.subtract(x, y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [63]:
x = [1, 2, 3, 4, 5]
y = 1
tf.subtract(y, x)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 0, -1, -2, -3, -4], dtype=int32)>

In [64]:
# tf.math.multiply
import tensorflow as tf
x = tf.constant(([1, 2, 3, 4]))
tf.math.multiply(x, x)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16], dtype=int32)>

In [65]:
tf.multiply(x, x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16], dtype=int32)>

In [66]:
tf.math.multiply(7,6)


<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [67]:
x = tf.ones([1, 2]);
y = tf.ones([2, 1]);
x * y

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [68]:
# tf.math.maximum

x = tf.constant([0., 0., 0., 0.])
y = tf.constant([-2., 0., 2., 5.])
tf.math.maximum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 2., 5.], dtype=float32)>

In [69]:
x = tf.constant([-5., 0., 0., 0.])
y = tf.constant([-3.])
tf.math.maximum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-3.,  0.,  0.,  0.], dtype=float32)>

In [70]:
# tf.math.minimum
x = tf.constant([0., 0., 0., 0.])
y = tf.constant([-5., -2., 0., 3.])
tf.math.minimum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5., -2.,  0.,  0.], dtype=float32)>

In [71]:
x = tf.constant([-5., 0., 0., 0.])
y = tf.constant([-3.])
tf.math.minimum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5., -3., -3., -3.], dtype=float32)>

In [72]:
# tf.math.log
x = tf.constant([0, 0.5, 1, 5])
tf.math.log(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([      -inf, -0.6931472,  0.       ,  1.609438 ], dtype=float32)>

In [73]:
# tf.math.divide
x = tf.constant([16, 12, 11])
y = tf.constant([4, 6, 2])
tf.divide(x,y)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , 2. , 5.5])>

In [74]:
# tf.math.pow
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [75]:
# tf.math.sqrt
x = tf.constant([[4.0], [16.0]])
tf.sqrt(x)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [4.]], dtype=float32)>

In [76]:
y = tf.constant([[-4.0], [16.0]])
tf.sqrt(y)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[nan],
       [ 4.]], dtype=float32)>

In [77]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [78]:
tf.ones((1)),tf.float32

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 tf.float32)

In [79]:
ones_2d= tf.ones((2,2)),tf.float32
ones_2d

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 tf.float32)

In [80]:
ones_3d=tf.ones((2,2,4),tf.float32)

In [81]:
ones_3d

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [82]:
tf.zeros(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [83]:
zeros_2d=tf.zeros((2,2),dtype=tf.int32)
zeros_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [84]:
# Ones_like:Creates a tensor of all ones that has the same shape as the input.
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
tf.ones_like(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [85]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
tf.zeros_like(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

## **Placeholder**-Migrate tensorflow 1 code to tensorflow 2
Place holder is a variable that we will assign data to at a later date.

In [86]:
import tensorflow as tf

In [87]:
tf.placeholder(dtype.float32,shape=(400,400))

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [ ]:
tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))

In [ ]:
tf.compat.v1.disable_eager_execution()

In [ ]:
a=tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))
a

In [ ]:
b=tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))
b

In [ ]:
c=tf.add(a,b)
c

In [ ]:
import numpy as np

In [ ]:
ones_array=np.ones((400,400),np.float32)
ones_array

In [ ]:
with tf.compat.v1.Session() as sess:
   d=sess.run(c,feed_dict={a:ones_array,b:ones_array})

In [ ]:
d

## **Sparse Tensors**
It enables efficient storage & processing of tensors that contains lot of zero values

In [ ]:
tf.SparseTensor()


In [ ]:
tf.SparseTensor(indices=[[0,3],[2,4]],values=[10,20],dense_shape=[3,10])

In [ ]:
st1=tf.SparseTensor(indices=[[0,3],[2,4]],values=[10,20],dense_shape=[3,10])
st1

In [ ]:
print(st1)

In [ ]:
import tensorflow as tf

x = tf.compat.v1.get_variable("x", dtype=tf.int32,  initializer=tf.constant([5]))
y = tf.compat.v1.get_variable("y", dtype=tf.int32,  initializer=tf.constant([6]))


In [ ]:
c = tf.constant([5], name ="constant")
square = tf.constant([2], name ="square")
f = tf.multiply(x, y) + tf.pow(x, square) + y + c
f
